import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";

export const metadata: Metadata = {
  title: "Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
