import type { Metadata } from "next";
import "../globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={" px-4 font-inter"}>
        <header className="main-container">
          <div>
            <Image
              src={"/assets/images/logo.svg"}
              width={auto}
              height={auto}
              alt="Stack"
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
